.PHONY: dev prod down logs migrate migrate-create test-api test-web lint build setup shell-api shell-web ps clean

# ─── Compose file shortcuts ───────────────────────────────────────────────────

COMPOSE_BASE := docker-compose -f docker-compose.yml
COMPOSE_DEV  := $(COMPOSE_BASE) -f docker-compose.dev.yml

# ─── Local development ────────────────────────────────────────────────────────

## Start all services with hot-reload, pgadmin, and redis-commander
dev:
	$(COMPOSE_DEV) up

## Start all services in detached mode (dev)
dev-d:
	$(COMPOSE_DEV) up -d

## Start production stack (detached)
prod:
	$(COMPOSE_BASE) up -d

## Stop and remove containers (keeps volumes)
down:
	$(COMPOSE_DEV) down

## Stop and remove containers AND volumes (full reset — destroys data)
down-v:
	@read -p "This will delete all database data. Are you sure? [y/N] " confirm; \
	[ "$$confirm" = "y" ] || exit 1
	$(COMPOSE_DEV) down -v

## Build all Docker images
build:
	$(COMPOSE_BASE) build

## Build without cache
build-no-cache:
	$(COMPOSE_BASE) build --no-cache

# ─── Database ─────────────────────────────────────────────────────────────────

## Apply all pending Alembic migrations
migrate:
	$(COMPOSE_DEV) exec api alembic upgrade head

## Roll back one migration
migrate-down:
	$(COMPOSE_DEV) exec api alembic downgrade -1

## Create a new autogenerated migration (usage: make migrate-create name="your message")
migrate-create:
	@test -n "$(name)" || (echo "Usage: make migrate-create name='your migration message'" && exit 1)
	$(COMPOSE_DEV) exec api alembic revision --autogenerate -m "$(name)"

## Show current migration status
migrate-status:
	$(COMPOSE_DEV) exec api alembic current

# ─── Testing ──────────────────────────────────────────────────────────────────

## Run Python tests
test-api:
	$(COMPOSE_DEV) exec api pytest -x -v

## Run Python tests with coverage report
test-api-cov:
	$(COMPOSE_DEV) exec api pytest --cov=app --cov-report=term-missing

## Run frontend tests
test-web:
	$(COMPOSE_DEV) exec web npm test -- --watchAll=false

## Run all tests
test: test-api test-web

# ─── Linting & Type Checking ──────────────────────────────────────────────────

## Run all linters
lint:
	$(COMPOSE_DEV) exec api ruff check .
	$(COMPOSE_DEV) exec api mypy app
	$(COMPOSE_DEV) exec web npm run lint

## Auto-fix linting issues where possible
lint-fix:
	$(COMPOSE_DEV) exec api ruff check . --fix
	$(COMPOSE_DEV) exec web npm run lint -- --fix

## Format Python code
format:
	$(COMPOSE_DEV) exec api ruff format .

# ─── Logs ─────────────────────────────────────────────────────────────────────

## Tail logs for all services (or specific: make logs service=api)
logs:
	$(COMPOSE_DEV) logs -f $(service)

## Show last 100 lines for each service
logs-all:
	$(COMPOSE_DEV) logs --tail=100

# ─── Shells ───────────────────────────────────────────────────────────────────

## Open a shell in the API container
shell-api:
	$(COMPOSE_DEV) exec api bash

## Open a shell in the web container
shell-web:
	$(COMPOSE_DEV) exec web sh

## Open psql
shell-db:
	$(COMPOSE_DEV) exec postgres psql -U $${DATABASE_USER:-voiceai} -d $${DATABASE_NAME:-voiceai}

## Open redis-cli
shell-redis:
	$(COMPOSE_DEV) exec redis redis-cli

# ─── Utilities ────────────────────────────────────────────────────────────────

## Show running containers
ps:
	$(COMPOSE_DEV) ps

## First-time project setup
setup:
	@command -v docker >/dev/null 2>&1 || (echo "ERROR: docker is not installed" && exit 1)
	@command -v docker-compose >/dev/null 2>&1 || docker compose version >/dev/null 2>&1 || (echo "ERROR: docker-compose is not installed" && exit 1)
	@if [ ! -f .env ]; then \
		cp .env.example .env; \
		echo "Copied .env.example to .env"; \
		echo "Generating secure keys..."; \
		python3 scripts/generate-keys.py >> .env; \
	else \
		echo ".env already exists — skipping copy"; \
	fi
	@echo ""
	@echo "Setup complete. Next steps:"
	@echo "  1. Edit .env with your API keys"
	@echo "  2. Run: make dev"
	@echo "  3. In another terminal: make migrate"

## Remove all stopped containers and dangling images
clean:
	docker system prune -f

## Generate new SECRET_KEY and ENCRYPTION_KEY (prints to stdout)
generate-keys:
	python3 scripts/generate-keys.py

## Seed demo workspace and user
seed-demo:
	$(COMPOSE_DEV) exec api python scripts/seed-demo.py

## Print help
help:
	@grep -E '^## ' Makefile | sed 's/## /  /'
	@echo ""
	@echo "Usage examples:"
	@echo "  make dev"
	@echo "  make logs service=api"
	@echo "  make migrate-create name='add user preferences'"
